### ISSUE TITLE
Crash on irrigation stop

### ISSUE THREAD

**Issue by heuels** [heuels/briskhome-irrigation#1]
Originally reported by: **Egor Zaitsev (Bitbucket: [ezaitsev](https://bitbucket.org/ezaitsev), GitHub: [ezaitsev](https://github.com/ezaitsev))**

----------------------------------------

```
[2016-04-30 16:14:12] WARN: Работа модуля была завершена некорректно (/opt/briskhome-plugins/briskhome-irrigation/irrigation.js:276)
	Код: 6
	Ошибка: При инициализации обнаружен включенный полив контура
	Подробная информация: 
	    {
	        "Контур": "greenhouse"
	    }
[2016-04-30 16:14:12] TRACE: Обработка запроса на выключение полива контура (/opt/briskhome-plugins/briskhome-irrigation/irrigation.js:506)
	Контур: greenhouse
[2016-04-30 16:14:12] INFO: Полив контура выключен (/opt/briskhome-plugins/briskhome-irrigation/irrigation.js:535)
	Контур: greenhouse
При работе приложения произошло необработанное исключение
/opt/briskhome/briskhome.js:36
  throw(err);
  ^

SyntaxError: Unexpected end of input
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/opt/briskhome-plugins/briskhome-irrigation/irrigation.js:528:37)
    at emitOne (events.js:78:13)
    at IncomingMessage.emit (events.js:170:7)
    at readableAddChunk (_stream_readable.js:147:16)
    at IncomingMessage.Readable.push (_stream_readable.js:111:10)
    at HTTPParser.parserOnBody (_http_common.js:110:22)
    at Socket.socketOnData (_http_client.js:312:20)
    at emitOne (events.js:78:13)
    at Socket.emit (events.js:170:7)
    at readableAddChunk (_stream_readable.js:147:16)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:524:20)
```

----------------------------------------
- Bitbucket: https://bitbucket.org/briskhome/briskhome-irrigation/issue/1

**Comment by heuels** [comment]
*Original comment by* **Egor Zaitsev (Bitbucket: [ezaitsev](https://bitbucket.org/ezaitsev), GitHub: [ezaitsev](https://github.com/ezaitsev))**:

----------------------------------------

Проблема устранена в версии `0.1.5` (e60fa1f).
