### ISSUE TITLE
Crash on JSON.parse

### ISSUE THREAD

**Issue by heuels** [heuels/briskhome-irrigation#3]
Originally reported by: **Egor Zaitsev (Bitbucket: [ezaitsev](https://bitbucket.org/ezaitsev), GitHub: [ezaitsev](https://github.com/ezaitsev))**

----------------------------------------

Модуль неоднократно аварийно завершал работу из-за ошибки при парсинге JSON, полученного от контроллера. Необходимо настроить вывод полученных сообщений в `log.trace` и устранить ошибку.
```javascript

[2016-05-03 19:51:20] INFO: Получен запрос с маркером аутентификации '12345abc' (/opt/briskhome/lib/core.api/index.js:56)
{ name: 'garden', status: false }
[2016-05-03 19:51:20] INFO: Полив контура выключен (/opt/briskhome/node_modules/briskhome-irrigation/irrigation.js:546)
        Контур: garden
При работе приложения произошло необработанное исключение
SyntaxError: Unexpected token a
    at Object.parse (native)
    at IncomingMessage.<anonymous> (/opt/briskhome/node_modules/briskhome-irrigation/irrigation.js:60:35)
    at emitNone (events.js:85:20)
    at IncomingMessage.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:913:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
 <-- Приложение аварийно завершило работу
```

----------------------------------------
- Bitbucket: https://bitbucket.org/briskhome/briskhome-irrigation/issue/3

**Comment by heuels** [comment]
*Original comment by* **Egor Zaitsev (Bitbucket: [ezaitsev](https://bitbucket.org/ezaitsev), GitHub: [ezaitsev](https://github.com/ezaitsev))**:

----------------------------------------

В развернутый на сервере код добавлен обработчик, который будет писать в лог полученные от контроллера данные. При повторении ошибки задача будет дополнена конкрентыми причинами ошибки.

**Comment by heuels** [comment]
*Original comment by* **Egor Zaitsev (Bitbucket: [ezaitsev](https://bitbucket.org/ezaitsev), GitHub: [ezaitsev](https://github.com/ezaitsev))**:

----------------------------------------

Коммит 4f74a6c устраняет ошибку.
